### ISSUE TITLE
Installing by is broken

### ISSUE THREAD

**Issue by humitos** [humitos/linkodeit#13]
```
Collecting linkodeit
  Downloading linkodeit-0.5.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-TbpaTZ/linkodeit/setup.py", line 6, in <module>
        linkodeit = imp.load_source(name='linkodeit', pathname='linkodeit/linkodeit')
    TypeError: load_source() takes no keyword arguments
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-TbpaTZ/linkodeit/setup.py", line 6, in <module>
    
        linkodeit = imp.load_source(name='linkodeit', pathname='linkodeit/linkodeit')
    
    TypeError: load_source() takes no keyword arguments
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-TbpaTZ/linkodeit
```

**Comment by humitos** [comment]
It's not compatible with python2.

That's the problem.
